import {createWarning} from './voice.mjs?v=stage52';
import {Run,GATE_COUNT,W,H,SHIP_Y,RADIUS,LANES,SHIP_SPEED,clamp,gapWidth} from './physics.mjs?v=stage52';
const warning=createWarning(window.speechSynthesis,window.SpeechSynthesisUtterance);
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let mode='manual',run=null,active=false,paused=false,available=false,keys=new Set(),drag=false,pointerId=null,lastPointerX=null,pointerX=null,previous=performance.now(),accumulator=0,lastPoll=0,pending=false,epoch=0,abort=null,apiCount=0,times=[],probabilities=[],plans=new Map(),decision='',sound=false,audio=null,done=false,results=[];
try{results=JSON.parse(localStorage.getItem('shutter-run-results')||'[]').slice(-6)}catch{}
let base=new URLSearchParams(location.search).get('api')||'';$('backend').value=base;
function endpoint(path){return base?base.replace(/\/$/,'')+path:path}
function message(text){$('notice').textContent=text}
function modeLabel(){return mode==='api'?'DECISIONS API / LIVE':mode==='reference'?'AUTO DEMO / NO AI / API OFF':'MANUAL / API OFF'}
function changeMode(value){if(active){message('比較条件を保つため、操縦モードは次の出撃から変更できます。');return}mode=value;$('manual').classList.toggle('selected',mode==='manual');$('api-mode').classList.toggle('selected',mode==='api');$('reference').classList.toggle('selected',mode==='reference');$('flight-mode').textContent=modeLabel();$('start').disabled=mode==='api'&&!available;$('overlay-start').disabled=mode==='api'&&!available;$('api-dot').classList.toggle('live',mode==='api'&&available);$('decision-message').textContent=mode==='api'?(available?'実APIから進路を選択':'実APIサーバーへの接続が必要です'):mode==='reference'?'AIなし自動デモ · API呼び出しなし':'手動操縦 · API呼び出しなし';if(mode==='api'&&!available){document.querySelector('details').open=true;message('実APIは未接続です。手動操縦はすぐにプレイできます。')}else message('同じSEED・コースなら、手動も自動も同じシャッターと速度です。')}
async function connect(){let value=$('backend').value.trim();try{if(value){const u=new URL(value);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('HTTPSまたはlocalhostを指定してください。');base=u.origin}else base='';const res=await fetch(endpoint('/api/config'),{signal:AbortSignal.timeout(4000)});if(!res.ok)throw Error('接続用サーバーが見つかりません。');const info=await res.json();available=info.available===true&&info.model==='gpt-6-luna';$('api-state').textContent=available?'gpt-6-luna · 接続済み':'APIキー未設定';$('connection-note').textContent=available?'接続済み。API自動操縦を選んで出撃できます。':'サーバーにOPENAI_API_KEYを設定してください。'}catch(e){available=false;$('api-state').textContent='未接続';$('connection-note').textContent='実APIは未接続。手動・ローカル参考操縦はプレイできます。'}changeMode(mode)}
async function ask(initial=false){if(pending||!run||run.status!=='running'||mode!=='api')return;pending=true;lastPoll=performance.now();const current=epoch,observed=run.observation(),gate=observed.shutters[0]?.id,start=performance.now();abort=new AbortController();const timeout=setTimeout(()=>abort?.abort(),1800);try{const response=await fetch(endpoint('/api/decide'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:observed}),signal:abort.signal});const data=await response.json();if(!response.ok)throw Error(data.error||`HTTP ${response.status}`);if(data.provider!=='openai_decisions'||!/^lane_[1-5]$/.test(data.choice))throw Error('Decisions APIの応答形式が一致しません。');if(current!==epoch||run.status!=='running')return;apiCount++;times.push(performance.now()-start);times=times.slice(-200);probabilities=Array.isArray(data.probabilities)?data.probabilities:[];for(const plan of data.plans||[{gate_id:gate,choice:data.choice,probabilities:data.probabilities}]){if(Number.isInteger(plan.gate_id)&&/^lane_[1-5]$/.test(plan.choice))plans.set(plan.gate_id,plan)}const nearest=run.observation().shutters[0]?.id,currentPlan=plans.get(nearest);if(currentPlan){run.target=LANES[Number(currentPlan.choice.at(-1))-1];probabilities=currentPlan.probabilities||[];decision=`GATE ${String(nearest).padStart(2,'0')} → LANE ${currentPlan.choice.at(-1)} / 先読み`} if(initial){active=true;paused=false;$('overlay').classList.add('hidden');canvas.focus({preventScroll:true})}updateProbabilities();tone(680,.028,.025)}catch(e){if(current!==epoch)return;warning.stop();active=initial?false:active;paused=true;$('difficulty').disabled=false;$('seed').disabled=false;showOverlay('API CONNECTION ERROR','API判断を取得できませんでした。','手動モードで試すか、サーバーの接続を確認してください。API失敗時にローカル回避へ置き換えません。','再試行 →');message(String(e.message));$('decision-message').textContent='APIエラーで停止 · 成績には記録しません';done=true}finally{clearTimeout(timeout);if(current===epoch){pending=false;abort=null}}}
function showOverlay(tag,title,text,button){$('overlay-tag').textContent=tag;$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('overlay-start').textContent=button;$('overlay').classList.remove('hidden')}
function start(){if(mode==='api'&&!available){changeMode('api');return}warning.arm();epoch++;abort?.abort();pending=false;keys.clear();resetDrag();accumulator=0;done=false;paused=false;apiCount=0;times=[];probabilities=[];plans.clear();decision='';lastPoll=0;const seed=clamp(Math.trunc(Number($('seed').value)||1024),1,4294967295);$('seed').value=seed;run=new Run({seed,difficulty:$('difficulty').value,mode});$('flight-mode').textContent=modeLabel();$('overlay').classList.add('hidden');$('pause').textContent='一時停止';$('difficulty').disabled=true;$('seed').disabled=true;updateProbabilities();tone(220,.15,.06);if(mode==='api'){active=false;showOverlay('CONNECTING TO DECISIONS','最初の進路を判断中…','最初のAPI応答を受け取ってから出撃します。','判断待ち');$('overlay-start').disabled=true;ask(true).finally(()=>{$('overlay-start').disabled=false})}else{active=true;canvas.focus({preventScroll:true})}message(mode==='reference'?'AIなし自動デモです。ローカル処理で操縦し、API呼び出しはありません。':'シャッターの開口部へ。速度は時間とともに上がり続けます。')}
function togglePause(){if(!active||done)return;paused=!paused;if(paused)warning.stop();else warning.arm();keys.clear();resetDrag();$('pause').textContent=paused?'再開':'一時停止';if(paused)showOverlay('PAUSED','一時停止','同じ位置・速度から再開できます。','再開 →');else{$('overlay').classList.add('hidden');canvas.focus({preventScroll:true})}}
function finish(){if(done)return;done=true;active=false;warning.stop();$('difficulty').disabled=false;$('seed').disabled=false;abort?.abort();const clear=run.status==='cleared';showOverlay(clear?'ESCAPE COMPLETE':'HULL LOST',clear?'回廊、突破。':'シャッターに接触。',`${run.passed} / ${GATE_COUNT} 突破 · ${run.time.toFixed(1)} 秒 · 最高 ${Math.round(run.speed)} px/s${mode==='reference'?' · ローカル参考操縦':''}`,'同じコースで再挑戦 →');tone(clear?880:90,.35,.08);results.push({total:GATE_COUNT,seed:run.seed,difficulty:run.difficulty,mode,passed:run.passed,time:+run.time.toFixed(1),speed:Math.round(run.speed),clear,latency:times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length):null,calls:apiCount});results=results.slice(-6);try{localStorage.setItem('shutter-run-results',JSON.stringify(results))}catch{}renderResults()}
function renderResults(){const host=$('results');host.replaceChildren();for(const item of results.slice().reverse()){const div=document.createElement('div');div.className='result';const strong=document.createElement('strong');strong.textContent=`${item.mode==='api'?'実API':item.mode==='reference'?'AIなし自動デモ':'手動'} · ${item.clear?'CLEAR':`${item.passed}/${item.total||26}`}`;div.append(strong,document.createElement('br'),document.createTextNode(`SEED ${item.seed} / ${item.difficulty.toUpperCase()} · ${item.time}s · ${item.speed} px/s${item.latency!==null?` · ${item.latency}ms / ${item.calls} calls`:''}`));host.append(div)}if(!results.length)host.textContent='プレイ結果がここに残ります。'}
function updateProbabilities(){const host=$('probabilities');host.replaceChildren();if(mode!=='api')return;for(let i=0;i<5;i++){const p=probabilities.find(p=>p.value===`lane_${i+1}`)?.probability||0;const row=document.createElement('div');row.className='probability';const name=document.createElement('span');name.textContent=`LANE ${i+1}`;const track=document.createElement('i'),bar=document.createElement('b');bar.style.width=`${clamp(p,0,1)*100}%`;track.append(bar);const value=document.createElement('em');value.textContent=`${Math.round(p*100)}%`;row.append(name,track,value);host.append(row)}}
function tone(hz,duration,volume){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=hz;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch{}}
function render(now){const state=run||new Run();const d=run?state.distance:now*.045,speed=state.speed;ctx.fillStyle='#07121e';ctx.fillRect(0,0,W,H);const gradient=ctx.createLinearGradient(0,0,W,0);gradient.addColorStop(0,'#162534');gradient.addColorStop(.5,'#081621');gradient.addColorStop(1,'#162534');ctx.fillStyle=gradient;ctx.fillRect(24,0,W-48,H);
 ctx.strokeStyle='#233c4e';ctx.lineWidth=1;for(let y=(d%72)-72;y<H;y+=72){ctx.beginPath();ctx.moveTo(26,y);ctx.lineTo(W-26,y);ctx.stroke();ctx.strokeStyle='#203441';for(let x=80;x<W-40;x+=80){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+72);ctx.stroke()}}
 for(let y=(d%120)-120;y<H;y+=120){ctx.fillStyle='#132735';ctx.fillRect(0,y,24,95);ctx.fillRect(W-24,y,24,95);ctx.fillStyle='#69d1ce';ctx.shadowColor='#66dfd4';ctx.shadowBlur=8;ctx.fillRect(12,y+12,3,24);ctx.fillRect(W-15,y+12,3,24);ctx.shadowBlur=0}
 for(let i=0;i<45;i++){const x=32+(i*173)%416,y=(i*133+d*(1+i%3*.24))%H;ctx.fillStyle=i%5===0?'#57a8ba':'#3a5b6e';ctx.fillRect(x,y,1,speed>500?12:4)}
 for(const gate of state.gates){const remaining=gate.distance-state.distance,y=SHIP_Y-remaining;if(y<-65||y>H+65)continue;const width=gapWidth(remaining),left=gate.center-width/2,right=gate.center+width/2;for(const [x,w] of [[24,Math.max(0,left-24)],[right,Math.max(0,W-24-right)]]){if(w<=0)continue;ctx.fillStyle='#283c4b';ctx.fillRect(x,y-13,w,26);ctx.fillStyle='#4c6170';ctx.fillRect(x,y-13,w,5);ctx.fillStyle='#111e2a';ctx.fillRect(x,y+8,w,5);ctx.save();ctx.beginPath();ctx.rect(x,y-7,w,13);ctx.clip();ctx.fillStyle='#b58444';for(let stripe=x-15;stripe<x+w;stripe+=24){ctx.beginPath();ctx.moveTo(stripe,y-7);ctx.lineTo(stripe+12,y-7);ctx.lineTo(stripe+24,y+6);ctx.lineTo(stripe+12,y+6);ctx.fill()}ctx.restore()}
 ctx.shadowBlur=13;ctx.shadowColor='#fa9065';ctx.fillStyle='#ffa77c';ctx.fillRect(left-3,y-15,3,30);ctx.fillRect(right,y-15,3,30);ctx.shadowBlur=0;ctx.fillStyle='#83c7d1';ctx.font='9px monospace';ctx.fillText(String(gate.id).padStart(2,'0'),gate.center-6,y-26);
 if(mode!=='manual'&&run){ctx.strokeStyle=mode==='api'?'#47d6cb66':'#879eac55';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(run.target,y+16);ctx.lineTo(run.x,SHIP_Y);ctx.stroke();ctx.setLineDash([])}}
 const x=state.x,y=SHIP_Y;ctx.save();ctx.translate(x,y);ctx.shadowColor=mode==='api'?'#5fe7d9':'#88c9ff';ctx.shadowBlur=16;ctx.fillStyle='#80cbfa';ctx.beginPath();ctx.moveTo(-7,16);ctx.lineTo(0,39+Math.sin(now*.025)*9);ctx.lineTo(7,16);ctx.fill();ctx.fillStyle='#d3e9f1';ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(10,-4);ctx.lineTo(23,15);ctx.lineTo(6,11);ctx.lineTo(0,17);ctx.lineTo(-6,11);ctx.lineTo(-23,15);ctx.lineTo(-10,-4);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#40adaf';ctx.fillRect(-3,-9,6,14);ctx.restore();
 if(run?.status==='crashed'){ctx.fillStyle='#ff735333';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#ffa179';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,38,0,Math.PI*2);ctx.stroke()}
 ctx.fillStyle='#ffffff03';for(let y=0;y<H;y+=4)ctx.fillRect(0,y,W,1);
 $('speed').textContent=Math.round(speed);$('speed-top').textContent=`${Math.round(speed)} PX/S`;$('acceleration').textContent=`+${state.acceleration} px/s² · ${speed>=state.maxSpeed?'MAX VELOCITY':'ACCELERATING'}`;$('passed').textContent=`${state.passed} / ${GATE_COUNT}`;$('gate-count').textContent=`GATE ${String(state.passed).padStart(2,'0')} / ${GATE_COUNT}`;$('clearance').textContent=Number.isFinite(state.clearance)?`${Math.max(0,Math.round(state.clearance))} px`:'—';$('timer').textContent=`00:${state.time.toFixed(1).padStart(4,'0')}`;$('progress-bar').style.width=`${clamp(state.distance/(state.gates.at(-1).distance+350)*100,0,100)}%`;$('calls').textContent=apiCount;$('latency').textContent=times.length?`${Math.round(times.at(-1))} ms`:'—';$('average').textContent=times.length?`${Math.round(times.reduce((a,b)=>a+b,0)/times.length)} ms`:'—';if(mode==='api'&&decision)$('decision-message').textContent=decision}
function frame(now){const delta=Math.min(.1,(now-previous)/1000);previous=now;if(active&&!paused&&!done){accumulator+=delta;while(accumulator>=1/120){if(mode==='reference')run.target=run.referenceTarget();if(mode==='api'){const g=run.observation().shutters[0]?.id,p=plans.get(g);if(p){run.target=LANES[Number(p.choice.at(-1))-1];if(decision!==`GATE ${String(g).padStart(2,'0')} → LANE ${p.choice.at(-1)} / 先読み`){decision=`GATE ${String(g).padStart(2,'0')} → LANE ${p.choice.at(-1)} / 先読み`;probabilities=p.probabilities||[];updateProbabilities()}}}let input=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);if(mode==='manual'&&pointerX!==null)input=clamp((pointerX-run.x)/(SHIP_SPEED/120),-1,1);run.step(1/120,input);accumulator-=1/120;if(run.status!=='running'){finish();break}}if(active&&!done)warning.tick(run);if(mode==='api'&&!pending&&now-lastPoll>=360&&run.observation().shutters.slice(0,3).some(g=>!plans.has(g.id)))ask()}render(now);requestAnimationFrame(frame)}
$('manual').onclick=()=>changeMode('manual');$('api-mode').onclick=()=>changeMode('api');$('reference').onclick=()=>changeMode('reference');$('start').onclick=start;$('overlay-start').onclick=()=>{if(paused&&active&&!done)togglePause();else start()};$('pause').onclick=togglePause;$('connect').onclick=connect;$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`音 ${sound?'ON':'OFF'}`;tone(500,.1,.05)};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','a','d',' '].includes(k))e.preventDefault();if(k===' '&&!e.repeat)togglePause();else if(k==='r'&&!e.repeat)start();else keys.add(k)});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();resetDrag()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active&&!paused&&!done)togglePause()});
function resetDrag(){const id=pointerId;drag=false;pointerId=null;lastPointerX=null;pointerX=null;if(id!==null&&canvas.hasPointerCapture(id))canvas.releasePointerCapture(id)}
canvas.addEventListener('pointerdown',e=>{if(mode!=='manual'||!active||paused||done||drag)return;drag=true;pointerId=e.pointerId;lastPointerX=e.clientX;pointerX=run.x;canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true})});
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==pointerId)return;pointerX=clamp(pointerX+(e.clientX-lastPointerX)/canvas.getBoundingClientRect().width*W,30,W-30);lastPointerX=e.clientX});
for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{if(e.pointerId===pointerId)resetDrag()});

$('voice').disabled=!warning.supported;$('voice').textContent=warning.supported?'音声警告 ON':'音声警告 非対応';$('voice').onclick=()=>{warning.setEnabled(!warning.enabled);$('voice').textContent=`音声警告 ${warning.enabled?'ON':'OFF'}`};
renderResults();connect();requestAnimationFrame(frame);
